services:
  db:
    container_name: db
    image: postgres:17
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  it-profile-backend:
    container_name: it-profile-backend
    image: abrodep/t1-it-profile-backend:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_KAFKA_SERVER: kafka:29092
  it-profile-frontend:
    container_name: it-profile-frontend
    image: abrodep/t1-it-profile-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - it-profile-backend