spring:
  application:
    name: Backend
  main:
    allow-circular-references: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${SPRING_KAFKA_SERVER:localhost:9092}
      properties:
        connections:
          max:
            idle:
              ms=10000:
        request:
          timeout:
            ms=30000:
        reconnect:
          backoff:
            ms=1000:
          max:
            ms=10000:
    consumer:
      group-id: technology
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: ${SPRING_KAFKA_SERVER:localhost:9092}
      properties:
        connections:
          max:
            idle:
              ms=10000:
        request:
          timeout:
            ms=30000:
        reconnect:
          backoff:
            ms=1000:
          max:
            ms=10000:
        spring:
          json:
            trusted:
              packages: "*"
            type:
              mapping: com.team5.techradar.model.dto.TechnologyPayloadResponse:com.it.backend.dto.response.TechnologyPayloadResponse
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    lifeTime: 300m

