create schema if not exists it_profile;

set search_path to it_profile;

create table if not exists positions(
    id bigint primary key generated by default as identity not null,
    name varchar(255),
    description text
);

create table if not exists specialists(
    id bigint primary key generated by default as identity not null,
    position_id bigint references positions(id),
    fio varchar(255),
    birthday varchar(255),
    sex varchar(255),
    city varchar(255)
);

create table if not exists soft_skills(
    id bigint primary key generated by default as identity not null,
    name varchar(255),
    description text
);

create table if not exists hard_skills(
    id bigint primary key generated by default as identity not null,
    name varchar(255),
    description text
);

create table if not exists specialists_soft_skills(
    specialist_id bigint references specialists(id),
    soft_skills_id bigint references soft_skills(id),
    level bigint check (level >= -1 and level <= 3),
    primary key (specialist_id, soft_skills_id)
);

create table if not exists positions_hard_skills(
    position_id bigint references positions(id),
    hard_skill_id bigint references hard_skills(id),
    primary key (position_id, hard_skill_id)
);

create table if not exists specialists_hard_skills(
    specialist_id bigint references specialists(id),
    hard_skill_id bigint references hard_skills(id),
    level bigint check (level >= -1 and level <= 3),
    primary key (specialist_id, hard_skill_id)
);