create schema if not exists it_profile;

set search_path to it_profile;

create table if not exists roles
(
    id   bigint primary key generated by default as identity not null,
    name varchar(255) unique                                 not null
);

create table if not exists api_clients
(
    id      bigint primary key generated by default as identity not null,
    token   varchar(255) unique                                 not null,
    role_id bigint references roles (id)
);

create table if not exists users
(
    id       bigint primary key generated by default as identity not null,
    username varchar(255) unique                                 not null,
    password varchar(255)                                        not null,
    role_id  bigint references roles (id)
);

create table if not exists positions
(
    id          bigint primary key generated by default as identity not null,
    name        varchar(255)                                        not null,
    description text
);

create table if not exists specialists
(
    id          bigint primary key generated by default as identity not null,
    user_id     bigint references users (id),
    position_id bigint references positions (id),
    surname     varchar(255)                                        not null,
    name        varchar(255)                                        not null,
    patronymic  varchar(255)                                        not null,
    birthday    date,
    sex         varchar(255)                                        not null,
    city        varchar(255)                                        not null
);

create table if not exists types
(
                                          id bigint primary key generated by default as identity not null,
                                          name varchar(255) not null
);

create table if not exists categories
(
                                               id bigint primary key generated by default as identity not null,
                                               type_id bigint references types(id) not null,
                                               name varchar(255) not null
);

create table if not exists levels
(
                                           id bigint primary key generated by default as identity not null,
                                           name varchar(255) not null,
                                           numeric_value int not null
);



create table if not exists assessment_processes
(
                                                   id bigint primary key generated by default as identity not null,
                                                   specialist_id bigint references specialists(id) not null,
                                                   created_by bigint references users(id) not null,
                                                   created_at timestamp(6) not null,
                                                   deadline timestamp(6) not null
);

create table if not exists scales
(
                                          id bigint primary key generated by default as identity not null,
                                          name varchar(255) not null
);

create table if not exists skills
(
                                     id bigint primary key generated by default as identity not null,
                                     type_id bigint references types(id) not null,
                                     category_id bigint references categories(id),
                                     scale_id bigint references scales(id) not null,
                                     name varchar(255) not null,
                                     description text,
                                     question text
);

create table if not exists specialist_skill
(
                                                 id bigint primary key generated by default as identity not null,
                                                 specialist_id bigint references specialists(id) not null,
                                                 skill_id bigint references skills(id) not null,
                                                 level_id bigint references levels(id),
                                                 date date
);

create table if not exists position_skill
(
                                               id bigint primary key generated by default as identity not null,
                                               position_id bigint references positions(id) not null,
                                               skill_id bigint references skills(id) not null
);

create table if not exists rates
(
                                    id bigint primary key generated by default as identity not null,
                                    scale_id bigint references scales(id) not null,
                                    description text not null,
                                    numeric_value int not null CHECK ( numeric_value >= 0 ),
                                    UNIQUE (scale_id, numeric_value)
);

create table if not exists assessors_skills_rates
(
                                                         id bigint primary key generated by default as identity not null,
                                                         assessment_process_id bigint references assessment_processes(id) not null,
                                                         assessor_id bigint references users(id) not null,
                                                         skill_id bigint references skills(id) not null,
                                                         rate_id bigint references rates(id)
);

create table if not exists skill_level
(
                                                  id bigint primary key generated by default as identity not null,
                                                  skill_id bigint references skills(id) not null,
                                                  level_id bigint references levels(id) not null,
                                                  description text not null,
                                                  development_way text not null
);

create table if not exists assessment_process_assessor_status
(
                                                  id bigint primary key generated by default as identity not null,
                                                  assessment_process_id bigint references assessment_processes(id) not null,
                                                  assessor_id bigint references users(id) not null,
                                                  status varchar(255) not null
);